src/routes/AnimalRoutes.py
from flask import Blueprint, request, redirect, url_for, render_template, flash
from src.services.AnimalService import AnimalService
from src.services.EmpresaService import EmpresaService
from src.services.TablaService import TablaService
from src.services.AuthService import AuthService

animal_blueprint = Blueprint('animal_blueprint', __name__)


@animal_blueprint.route('/list', methods=['GET'])
@AuthService.login_required
def list_animals():
    animals = AnimalService.get_all_animals()
    return render_template('animal/list.html', animals=animals)


@animal_blueprint.route('/view', methods=['GET', 'POST'])
@AuthService.login_required
def view_animal():
    filter_value = request.args.get('filter_value', '')
    filter_type = request.args.get('filter_type', 'id')

    if filter_value.strip() == "":
        if 'filter_value' in request.args:
            flash('Debes ingresar un valor de búsqueda', 'error')
        return render_template('animal/view.html')

    if filter_type == 'id':
        animales = AnimalService.get_animal_by_id(filter_value)
    else:
        flash('Tipo de filtro no válido', 'error')
        return redirect(url_for('animal_blueprint.list_animals'))

    if not animales:
        flash('Animal no encontrado', 'error')
        return render_template('animal/view.html')

    if isinstance(animales, dict):
        animales = [animales]

    return render_template('animal/view.html', animales=animales)


@animal_blueprint.route('/new', methods=['GET', 'POST'])
@AuthService.login_required
def new_animal_form():
    tipo_animal = TablaService.get_ftabla_by_id(12)
    estado_salud = TablaService.get_ftabla_by_id(5)
    if request.method == 'POST':
        data = request.form
        id_empresa = EmpresaService.get_id()
        tipo_tabla_tipo_animal = 12
        codigo_tabla_tipo_animal = data.get('codigo_tabla_tipo_animal')
        fecha_nacimiento = data.get('fecha_nacimiento')
        peso = data.get('peso')
        tipo_tabla_estado_salud = 5
        codigo_tabla_estado_salud = data.get('codigo_tabla_estado_salud')
        tipo_tabla_estado_registro = 13
        codigo_tabla_estado_registro = 1

        if not id_empresa or not codigo_tabla_tipo_animal or not fecha_nacimiento or not peso or not codigo_tabla_estado_salud:
            flash('Faltan datos obligatorios', 'error')
            return redirect(url_for('animal_blueprint.new_animal_form'))

        id_animal = AnimalService.create_animal(
            id_empresa=id_empresa,
            codigo_tabla_tipo_animal=codigo_tabla_tipo_animal,
            fecha_nacimiento=fecha_nacimiento,
            peso=peso,
            codigo_tabla_estado_salud=codigo_tabla_estado_salud,
            codigo_tabla_estado_registro=codigo_tabla_estado_registro,
            tipo_tabla_tipo_animal=tipo_tabla_tipo_animal,
            tipo_tabla_estado_salud=tipo_tabla_estado_salud,
            tipo_tabla_estado_registro=tipo_tabla_estado_registro
        )

        if id_animal:
            flash('Animal creado exitosamente', 'success')
            return redirect(url_for('animal_blueprint.view_animal', id_animal=id_animal))
        else:
            flash('Error al crear el animal', 'error')
            return render_template('animal/new.html', animal=None, tipo_animal=tipo_animal, estado_salud=estado_salud)

    return render_template('animal/new.html', animal=None, tipo_animal=tipo_animal, estado_salud=estado_salud)


@animal_blueprint.route('/edit', methods=['GET', 'POST'])
@AuthService.login_required
def edit_animal_form():
    tipo_animal = TablaService.get_ftabla_by_id(12)
    estado_salud = TablaService.get_ftabla_by_id(5)
    if request.method == 'POST':
        id_animal = request.form.get('id_animal')

        if not id_animal:
            flash('Debe proporcionar un ID de animal', 'error')
            return redirect(url_for('animal_blueprint.edit_animal_form'))

        animal = AnimalService.get_animal_by_id(id_animal)

        if isinstance(animal, list):
            animal = animal[0] if animal else None

        if not animal:
            flash('Animal no encontrado', 'error')
            return redirect(url_for('animal_blueprint.edit_animal_form'))

        return render_template('animal/edit.html', animal=animal, tipo_animal=tipo_animal, estado_salud=estado_salud)

    return render_template('animal/edit.html', animal=None, tipo_animal=tipo_animal, estado_salud=estado_salud)


@animal_blueprint.route('/update/<int:id_animal>', methods=['POST'])
@AuthService.login_required
def update_animal(id_animal):
    data = request.form
    id_empresa = EmpresaService.get_id()
    tipo_tabla_tipo_animal = 12
    codigo_tabla_tipo_animal = data.get('codigo_tabla_tipo_animal')
    fecha_nacimiento = data.get('fecha_nacimiento')
    peso = data.get('peso')
    tipo_tabla_estado_salud = 5
    codigo_tabla_estado_salud = data.get('codigo_tabla_estado_salud')

    if not id_empresa or not codigo_tabla_tipo_animal or not fecha_nacimiento or not peso or not codigo_tabla_estado_salud:
        flash('Faltan datos obligatorios', 'error')
        return redirect(url_for('animal_blueprint.edit_animal_form', animal=None, id_animal=id_animal))

    success = AnimalService.update_animal(
        id_animal=id_animal,
        id_empresa=id_empresa,
        codigo_tabla_tipo_animal=codigo_tabla_tipo_animal,
        fecha_nacimiento=fecha_nacimiento,
        peso=peso,
        codigo_tabla_estado_salud=codigo_tabla_estado_salud,
        tipo_tabla_tipo_animal=tipo_tabla_tipo_animal,
        tipo_tabla_estado_salud=tipo_tabla_estado_salud
    )

    if success:
        flash('Animal actualizado exitosamente', 'success')
        return redirect(url_for('animal_blueprint.view_animal', id_animal=id_animal))
    else:
        flash('Error al actualizar el animal', 'error')
        return redirect(url_for('animal_blueprint.edit_animal_form', animal=None, id_animal=id_animal))


@animal_blueprint.route('/delete/<int:id_animal>', methods=['POST'])
def delete_animal(id_animal):
    success = AnimalService.delete_animal(id_animal)

    if success:
        flash('Animal eliminado exitosamente', 'success')
    else:
        flash('Error al eliminar el animal', 'error')

    return redirect(url_for('animal_blueprint.list_animals'))

src/routes/IndexRoutes.py
from flask import Blueprint, render_template, jsonify, request
import traceback
from src.utils.Logger import Logger
from src.services.AuthService import AuthService

index_blueprint = Blueprint('index_blueprint', __name__)


@index_blueprint.route('/home')
def index():
    try:
        Logger.add_to_log("info", "{} {}".format(request.method, request.path))
        return render_template('home/home.html')
    except Exception as ex:
        Logger.add_to_log("error", str(ex))
        Logger.add_to_log("error", traceback.format_exc())

        response = jsonify({'message': "Internal Server Error Menu", 'success': False})
        return response, 500


@index_blueprint.route('/about')
def about():
    try:
        Logger.add_to_log("info", "{} {}".format(request.method, request.path))
        return render_template('home/about.html')
    except Exception as ex:
        Logger.add_to_log("error", str(ex))
        Logger.add_to_log("error", traceback.format_exc())

        response = jsonify({'message': "Internal Server Error", 'success': False})
        return response, 500


@index_blueprint.route('/contact')
def contact():
    try:
        Logger.add_to_log("info", "{} {}".format(request.method, request.path))
        return render_template('home/contact.html')
    except Exception as ex:
        Logger.add_to_log("error", str(ex))
        Logger.add_to_log("error", traceback.format_exc())

        response = jsonify({'message': "Internal Server Error", 'success': False})
        return response, 500


@index_blueprint.route('/menu')
@AuthService.login_required
def menu():
    try:
        Logger.add_to_log("info", "{} {}".format(request.method, request.path))
        return render_template('home/menu.html')
    except Exception as ex:
        Logger.add_to_log("error", str(ex))
        Logger.add_to_log("error", traceback.format_exc())

        response = jsonify({'message': "Internal Server Error", 'success': False})
        return response, 500

src/templates/animal/edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Editar Animal</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='global/edit.css') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js"></script>
    </head>

    <body>
        <header>
            <h1>Editar Animal</h1>
            <button class="home-icon" onclick="window.location.href='{{ url_for('index_blueprint.menu') }}'">
                <i class="fas fa-arrow-right"></i> Menu
            </button>
        </header>

        <!-- Bloque para mostrar mensajes flash -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <script>
                    {% for category, message in messages %}
                        Swal.fire({
                            icon: "{{ 'success' if category == 'success' else 'error' }}",
                            title: "{{ message }}",
                            showConfirmButton: false,
                            timer: 2000
                        });
                    {% endfor %}
                </script>
            {% endif %}
        {% endwith %}

        {% if not animal %}
            <!-- Formulario para obtener el ID del animal -->
            <form action="{{ url_for('animal_blueprint.edit_animal_form') }}" method="post">
                <label for="id_animal">ID del Animal:</label>
                <input type="number" id="id_animal" name="id_animal" required><br><br>
                <button type="submit">Cargar Animal</button>
            </form>
        {% else %}
            <!-- Formulario para editar el animal cargado -->
            <form action="{{ url_for('animal_blueprint.update_animal', id_animal=animal.id_animal) }}" method="post">
                <input type="hidden" name="id_animal" value="{{ animal.id_animal }}">

                <label for="tipo_animal">Tipo de Animal:</label>
                <select id="tipo_animal" name="codigo_tabla_tipo_animal" required>
                    <option value="" disabled selected>Seleccione una opción</option>
                    {% for tipo in tipo_animal %}
                        <option value="{{ tipo.id_valor }}" {% if tipo.id_valor == animal.codigo_tabla_tipo_animal %} selected {% endif %}>
                            {{ tipo.descripcion }}
                        </option>
                    {% endfor %}
                </select><br><br>

                <label for="fecha_nacimiento">Fecha de Nacimiento:</label>
                <input type="date" id="fecha_nacimiento" name="fecha_nacimiento" value="{{ animal.fecha_nacimiento }}" required><br><br>

                <label for="peso">Peso (kg):</label>
                <input type="number" id="peso" name="peso" value="{{ animal.peso }}" required><br><br>

                <label for="estado_salud">Estado de Salud:</label>
                <select id="estado_salud" name="codigo_tabla_estado_salud" required>
                    <option value="" disabled selected>Seleccione una opción</option>
                    {% for estado in estado_salud %}
                        <option value="{{ estado.id_valor }}" {% if estado.id_valor == animal.codigo_tabla_estado_salud %} selected {% endif %}>
                            {{ estado.descripcion }}
                        </option>
                    {% endfor %}
                </select><br><br>

                <button type="submit">Guardar Cambios</button>
                <a href="{{ url_for('index_blueprint.menu') }}">Cancelar</a>
            </form>
        {% endif %}
    </body>
</html>

src/templates/animal/list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Lista de Animales</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='global/list.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js"></script>
    </head>

    <body>
        <header>
            <h1>Lista de Animales</h1>
            <button class="home-icon" onclick="window.location.href='{{ url_for('index_blueprint.menu') }}'">
                <i class="fas fa-arrow-right"></i> Menu
            </button>
        </header>

        <!-- Bloque para mostrar mensajes flash -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <script>
                    {% for category, message in messages %}
                        Swal.fire({
                            icon: "{{ 'success' if category == 'success' else 'error' }}",
                            title: "{{ message }}",
                            showConfirmButton: false,
                            timer: 2000
                        });
                    {% endfor %}
                </script>
            {% endif %}
        {% endwith %}

        {% if animals %}
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tipo</th>
                        <th>Peso</th>
                        <th>Estado de Salud</th>
                    </tr>
                </thead>
                <tbody>
                    {% for animal in animals %}
                        <tr>
                            <td>{{ animal.id_animal }}</td>
                            <td>{{ animal.tipo_animal }}</td>
                            <td>{{ animal.peso }}</td>
                            <td>{{ animal.estado_salud }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No hay animales registrados.</p>
        {% endif %}
    </body>
</html>

src/templates/animal/new.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Nuevo Animal</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='global/new.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js"></script>
    </head>

    <body>
        <header>
            <h1>Nuevo Animal</h1>
            <button class="home-icon" onclick="window.location.href='{{ url_for('index_blueprint.menu') }}'">
                <i class="fas fa-arrow-right"></i> Menu
            </button>
        </header>

        <!-- Bloque para mostrar mensajes flash -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <script>
                    {% for category, message in messages %}
                        Swal.fire({
                            icon: "{{ 'success' if category == 'success' else 'error' }}",
                            title: "{{ message }}",
                            showConfirmButton: false,
                            timer: 2000
                        });
                    {% endfor %}
                </script>
            {% endif %}
        {% endwith %}

        <form action="{{ url_for('animal_blueprint.new_animal_form') }}" method="post">

            <label for="tipo_animal">Tipo de Animal:</label>
            <select id="tipo_animal" name="codigo_tabla_tipo_animal" required>
                <option value="" disabled selected>Seleccione una opción</option>
                {% for tipo in tipo_animal %}
                    <option value="{{ tipo.id_valor }}">
                        {{ tipo.descripcion }}
                    </option>
                {% endfor %}
            </select><br><br>

            <label for="fecha_nacimiento">Fecha de Nacimiento:</label>
            <input type="date" id="fecha_nacimiento" name="fecha_nacimiento" required><br><br>

            <label for="peso">Peso (kg):</label>
            <input type="number" id="peso" name="peso" required><br><br>

            <label for="estado_salud">Estado de Salud:</label>
            <select id="estado_salud" name="codigo_tabla_estado_salud" required>
                <option value="" disabled selected>Seleccione una opción</option>
                {% for estado in estado_salud %}
                    <option value="{{ estado.id_valor }}">
                        {{ estado.descripcion }}
                    </option>
                {% endfor %}
            </select><br><br>

            <button type="submit">Guardar</button>
            <a href="{{ url_for('index_blueprint.menu') }}">Cancelar</a>
        </form>
    </body>
</html>

src/templates/animal/view.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Detalles del Animal</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='global/view.css') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js"></script>
    </head>

    <body>
        <header>
            <h1>Detalles del Animal</h1>
            <button class="home-icon" onclick="window.location.href='{{ url_for('index_blueprint.menu') }}'">
                <i class="fas fa-arrow-right"></i> Menu
            </button>
        </header>

        <!-- Bloque para mostrar mensajes flash -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <script>
                    {% for category, message in messages %}
                        Swal.fire({
                            icon: "{{ 'success' if category == 'success' else 'error' }}",
                            title: "{{ message }}",
                            showConfirmButton: false,
                            timer: 2000
                        });
                    {% endfor %}
                </script>
            {% endif %}
        {% endwith %}

        <!-- Formulario de búsqueda -->
        <div class="search-container">
            <form action="{{ url_for('animal_blueprint.view_animal') }}" method="get">
                <label for="filter_type">Buscar por:</label>
                <div class="select-container">
                    <select id="filter_type" name="filter_type">
                        <option value="" disabled selected>Seleccione una opción</option>
                        <option value="id">ID</option>
                        <option value="nombre" disabled>Nombre</option>
                        <option value="apellido" disabled>Apellido</option>
                    </select>
                </div>

                <input type="text" id="filter_value" name="filter_value" placeholder="Valor de búsqueda" required>

                <button type="submit">Buscar</button>
            </form>
        </div>

        <!-- Mostrar múltiples registros -->
        {% if animales %}
            {% if animales|length > 1 %}
                <h2>Información de los Animales</h2>
                <table>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Tipo</th>
                            <th>Fecha de Nacimiento</th>
                            <th>Peso</th>
                            <th>Estado de salud</th>
                            <th>Estado del Registro</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for animal in animales %}
                            <tr>
                                <td>{{ animal.id_animal }}</td>
                                <td>{{ animal.tipo_animal }}</td>
                                <td>{{ animal.fecha_nacimiento }}</td>
                                <td>{{ animal.peso }}</td>
                                <td>{{ animal.estado_salud }}</td>
                                <td>{{ animal.estado_registro }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                {% set animal = animales[0] %}
                <!-- Detalles del animal cuando hay un solo registro -->
                <p><strong>ID:</strong> {{ animal.id_animal }}</p>
                <p><strong>Tipo:</strong> {{ animal.tipo_animal }}</p>
                <p><strong>Fecha de Nacimiento:</strong> {{ animal.fecha_nacimiento }}</p>
                <p><strong>Peso:</strong> {{ animal.peso }} kg</p>
                <p><strong>Estado de Salud:</strong> {{ animal.estado_salud }}</p>
                <p><strong>Estado de Registro:</strong> {{ animal.estado_registro }}</p>
            {% endif %}
        {% elif request.args %}
            <p>No se encontraron resultados para el filtro proporcionado.</p>
        {% endif %}
    </body>
</html>