src/routes/IndexRoutes.py
from flask import Blueprint, render_template, jsonify, request
import traceback
from src.utils.Logger import Logger
from src.services.AuthService import AuthService

index_blueprint = Blueprint('index_blueprint', __name__)


@index_blueprint.route('/home')
def index():
    try:
        Logger.add_to_log("info", "{} {}".format(request.method, request.path))
        return render_template('home/home.html')
    except Exception as ex:
        Logger.add_to_log("error", str(ex))
        Logger.add_to_log("error", traceback.format_exc())

        response = jsonify({'message': "Internal Server Error Menu", 'success': False})
        return response, 500


@index_blueprint.route('/about')
def about():
    try:
        Logger.add_to_log("info", "{} {}".format(request.method, request.path))
        return render_template('home/about.html')
    except Exception as ex:
        Logger.add_to_log("error", str(ex))
        Logger.add_to_log("error", traceback.format_exc())

        response = jsonify({'message': "Internal Server Error", 'success': False})
        return response, 500


@index_blueprint.route('/contact')
def contact():
    try:
        Logger.add_to_log("info", "{} {}".format(request.method, request.path))
        return render_template('home/contact.html')
    except Exception as ex:
        Logger.add_to_log("error", str(ex))
        Logger.add_to_log("error", traceback.format_exc())

        response = jsonify({'message': "Internal Server Error", 'success': False})
        return response, 500


@index_blueprint.route('/menu')
@AuthService.login_required
def menu():
    try:
        Logger.add_to_log("info", "{} {}".format(request.method, request.path))
        return render_template('home/menu.html')
    except Exception as ex:
        Logger.add_to_log("error", str(ex))
        Logger.add_to_log("error", traceback.format_exc())

        response = jsonify({'message': "Internal Server Error", 'success': False})
        return response, 500

src/routes/MonedaRoutes.py
from flask import Blueprint, request, redirect, url_for, render_template, flash
from src.services.MonedaService import MonedaService
from src.services.TablaService import TablaService
from src.services.AuthService import AuthService


monedas_blueprint = Blueprint('monedas_blueprint', __name__)


@monedas_blueprint.route('/list', methods=['GET'])
@AuthService.login_required
def list_monedas():
    monedas = MonedaService.get_all_monedas()
    return render_template('monedas/list.html', monedas=monedas)


@monedas_blueprint.route('/view', methods=['GET'])
@AuthService.login_required
def view_moneda():
    filter_value = request.args.get('filter_value', '')
    filter_type = request.args.get('filter_type', 'id')

    if filter_value.strip() == "":
        if 'filter_value' in request.args:
            flash('Debes ingresar un valor de búsqueda', 'error')
        return render_template('monedas/view.html')

    if filter_type == 'id':
        monedas = MonedaService.get_moneda_by_id(filter_value)
    else:
        flash('Tipo de filtro no válido', 'error')
        return redirect(url_for('monedas_blueprint.list_monedas'))

    if not monedas:
        flash('Moneda no encontrada', 'error')
        return render_template('monedas/view.html')

    if isinstance(monedas, dict):
        monedas = [monedas]

    return render_template('monedas/view.html', monedas=monedas)


@monedas_blueprint.route('/new', methods=['GET', 'POST'])
@AuthService.login_required
def new_moneda_form():
    tipo_moneda = TablaService.get_ftabla_by_id(15)
    if request.method == 'POST':
        data = request.form
        nombre = data.get('nombre').upper()
        tipo_tabla_tipo_moneda = 15
        codigo_tabla_tipo_moneda = data.get('codigo_tabla_tipo_moneda')

        if not nombre or not codigo_tabla_tipo_moneda:
            flash('Faltan datos obligatorios ', 'error')
            return redirect(url_for('monedas_blueprint.new_moneda_form'))

        id_moneda = MonedaService.create_moneda(
            nombre=nombre,
            codigo_tabla_tipo_moneda=codigo_tabla_tipo_moneda,
            tipo_tabla_tipo_moneda=tipo_tabla_tipo_moneda
        )

        if id_moneda:
            flash('Moneda creada exitosamente', 'success')
            return redirect(url_for('monedas_blueprint.view_moneda', id_moneda=id_moneda))
        else:
            flash('Error al crear el moneda', 'error')
            return render_template('monedas/new.html', monedas=None, tipo_moneda=tipo_moneda)

    return render_template('monedas/new.html', monedas=None, tipo_moneda=tipo_moneda)


@monedas_blueprint.route('/edit', methods=['GET', 'POST'])
@AuthService.login_required
def edit_moneda_form():
    tipo_moneda = TablaService.get_ftabla_by_id(15)
    if request.method == 'POST':
        id_moneda = request.form.get('id_moneda')
        nombre = request.form.get('nombre').upper()
        codigo_tabla_tipo_moneda = request.form.get('codigo_tabla_tipo_moneda')

        if not id_moneda or not nombre or not codigo_tabla_tipo_moneda:
            flash('Debe proporcionar un ID de moneda', 'error')
            return redirect(url_for('monedas_blueprint.edit_moneda_form'))

        monedas = MonedaService.get_moneda_by_id(id_moneda)

        if isinstance(monedas, list):
            monedas = monedas[0] if monedas else None

        if not monedas:
            flash('Moneda no encontrada', 'error')
            return redirect(url_for('monedas_blueprint.edit_moneda_form'))

        return render_template('monedas/edit.html', monedas=monedas, tipo_moneda=tipo_moneda)

    return render_template('monedas/edit.html', monedas=None, tipo_moneda=tipo_moneda)


@monedas_blueprint.route('/update/<int:id_moneda>', methods=['POST'])
@AuthService.login_required
def update_moneda(id_moneda):
    data = request.form
    nombre = data.get('nombre').upper()
    tipo_tabla_tipo_moneda = 15
    codigo_tabla_tipo_moneda = data.get('codigo_tabla_tipo_moneda')

    if not nombre or not codigo_tabla_tipo_moneda:
        flash('Faltan datos obligatorios', 'error')
        return redirect(url_for('monedas_blueprint.edit_moneda_form', id_moneda=id_moneda))

    success = MonedaService.update_moneda(
        id_moneda=id_moneda,
        nombre=nombre,
        codigo_tabla_tipo_moneda=codigo_tabla_tipo_moneda,
        tipo_tabla_tipo_moneda=tipo_tabla_tipo_moneda
    )

    if success:
        flash('Moneda actualizada exitosamente', 'success')
        return redirect(url_for('monedas_blueprint.view_moneda', id_moneda=id_moneda))
    else:
        flash('Error al actualizar el moneda', 'error')
        return redirect(url_for('monedas_blueprint.edit_moneda_form', id_moneda=id_moneda))

src/templates/monedas/edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Editar Rol</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='global/edit.css') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js"></script>
    </head>

    <body>
        <header>
            <h1>Editar Moneda</h1>
            <button class="home-icon" onclick="window.location.href='{{ url_for('index_blueprint.menu') }}'">
                <i class="fas fa-arrow-right"></i> Menu
            </button>
        </header>
    
        <!-- Bloque para mostrar mensajes flash -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <script>
                    {% for category, message in messages %}
                        Swal.fire({
                            icon: "{{ 'success' if category == 'success' else 'error' }}",
                            title: "{{ message }}",
                            showConfirmButton: false,
                            timer: 2000
                        });
                    {% endfor %}
                </script>
            {% endif %}
        {% endwith %}
    
        {% if not monedas %}
            <!-- Formulario para obtener el ID -->
            <form action="{{ url_for('monedas_blueprint.edit_moneda_form') }}" method="post">
                <label for="id_moneda">ID de la Moneda:</label>
                <input type="number" id="id_moneda" name="id_moneda" required><br><br>
                <button type="submit">Cargar Moneda</button>
            </form>
        {% else %}
            <!-- Formulario para editar la moneda cargada -->
            <form action="{{ url_for('monedas_blueprint.update_moneda', id_moneda=monedas.id_moneda) }}" method="post">
                <input type="hidden" name="id_moneda" value="{{ monedas.id_moneda }}">
        
                <label for="nombre">Nombre de la Moneda:</label>
                <input type="text" id="nombre" name="nombre" value="{{ monedas.nombre }}" required><br><br>

                <label for="tipo_moneda">Tipo de Moneda:</label>
                <select id="tipo_moneda" name="codigo_tabla_tipo_moneda" required>
                    <option value="" disabled selected>Seleccione una opción</option>
                    {% for tipo in tipo_moneda %}
                        <option value="{{ tipo.id_valor }}" {% if tipo.id_valor == monedas.codigo_tabla_tipo_moneda %} selected {% endif %}>
                            {{ tipo.descripcion }}
                        </option>
                    {% endfor %}
                </select><br><br>
        
                <button type="submit">Actualizar</button>
                <a href="{{ url_for('index_blueprint.menu') }}">Cancelar</a>
            </form>
        {% endif %}
    </body>
</html>

src/templates/monedas/list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Lista de Monedas</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='global/list.css') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js"></script>
    </head>

    <body>
        <header>
            <h1>Lista de Monedas</h1>
            <button class="home-icon" onclick="window.location.href='{{ url_for('index_blueprint.menu') }}'">
                <i class="fas fa-arrow-right"></i> Menu
            </button>
        </header>

        <!-- Bloque para mostrar mensajes flash -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <script>
                    {% for category, message in messages %}
                        Swal.fire({
                            icon: "{{ 'success' if category == 'success' else 'error' }}",
                            title: "{{ message }}",
                            showConfirmButton: false,
                            timer: 2000
                        });
                    {% endfor %}
                </script>
            {% endif %}
        {% endwith %}

    {% if monedas %}
        <table>
            <thead>
            <tr>
                <th>ID</th>
                <th>Nombre de la Moneda</th>
                <th>Tipo de Moneda</th>
            </tr>
            </thead>
            <tbody>
            {% for moneda in monedas %}
                <tr>
                    <td>{{ moneda.id_moneda }}</td>
                    <td>{{ moneda.nombre }}</td>
                    <td>{{ moneda.tipo_moneda }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No hay monedas registradas.</p>
    {% endif %}
    </body>
</html>

src/templates/monedas/new.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Nueva Moneda</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='global/new.css') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js"></script>
    </head>

    <body>
        <header>
            <h1>Nueva Moneda</h1>
            <button class="home-icon" onclick="window.location.href='{{ url_for('index_blueprint.menu') }}'">
                <i class="fas fa-arrow-right"></i> Menu
            </button>
        </header>

        <!-- Bloque para mostrar mensajes flash -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <script>
                    {% for category, message in messages %}
                        Swal.fire({
                            icon: "{{ 'success' if category == 'success' else 'error' }}",
                            title: "{{ message }}",
                            showConfirmButton: false,
                            timer: 2000
                        });
                    {% endfor %}
                </script>
            {% endif %}
        {% endwith %}

        <form action="{{ url_for('monedas_blueprint.new_moneda_form') }}" method="post">
            <label for="nombre">Nombre de la Moneda:</label>
            <input type="text" id="nombre" name="nombre" required><br><br>

            <label for="tipo_moneda">Tipo de Moneda:</label>
            <select id="tipo_moneda" name="codigo_tabla_tipo_moneda" required>
                <option value="" disabled selected>Seleccione una opción</option>
                {% for tipo in tipo_moneda %}
                    <option value="{{ tipo.id_valor }}">
                        {{ tipo.descripcion }}
                    </option>
                {% endfor %}
            </select><br><br>

            <button type="submit">Guardar</button>
            <a href="{{ url_for('index_blueprint.menu') }}">Cancelar</a>
        </form>
    </body>
</html>

src/templates/monedas/view.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Detalles de la Moneda</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='global/view.css') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js"></script>
    </head>

    <body>
        <header>
            <h1>Detalles de la Moneda</h1>
            <button class="home-icon" onclick="window.location.href='{{ url_for('index_blueprint.menu') }}'">
                <i class="fas fa-arrow-right"></i> Menu
            </button>
        </header>

        <!-- Bloque para mostrar mensajes flash -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <script>
                    {% for category, message in messages %}
                        Swal.fire({
                            icon: "{{ 'success' if category == 'success' else 'error' }}",
                            title: "{{ message }}",
                            showConfirmButton: false,
                            timer: 2000
                        });
                    {% endfor %}
                </script>
            {% endif %}
        {% endwith %}

        <!-- Formulario de búsqueda -->
        <div class="search-container">
            <form action="{{ url_for('monedas_blueprint.view_moneda') }}" method="get">
                <label for="filter_type">Buscar por:</label>
                <div class="select-container">
                    <select id="filter_type" name="filter_type">
                        <option value="" disabled selected>Seleccione una opción</option>
                        <option value="id">ID</option>
                        <option value="tipo_moneda" disabled>Tipo de Moneda</option>
                    </select>
                </div>

                <input type="text" id="filter_value" name="filter_value" placeholder="Valor de búsqueda" required>

                <button type="submit">Buscar</button>
            </form>
        </div>

        <!-- Mostrar múltiples registros -->
        {% if monedas %}
            {% if monedas|length > 1 %}
                <h2>Información de las Monedas</h2>
                <table>
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre de la Moneda</th>
                        <th>Tipo de Moneda</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for moneda in monedas %}
                        <tr>
                            <td>{{ moneda.id_moneda }}</td>
                            <td>{{ moneda.nombre }}</td>
                            <td>{{ moneda.tipo_moneda }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                {% set moneda = monedas[0] %}
                <!-- Detalles de la moneda cuando hay un solo registro -->
                <p><strong>ID de la Moneda:</strong> {{ moneda.id_moneda }}</p>
                <p><strong>Nombre de la Moneda:</strong> {{ moneda.nombre }}</p>
                <p><strong>Tipo de Moneda:</strong> {{ moneda.tipo_moneda }}</p>
            {% endif %}
        {% elif request.args %}
            <p>No se encontraron resultados para el filtro proporcionado.</p>
        {% endif %}
    </body>
</html>